package com.ghInternship.GHInternship2026.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * User entity — represents the 'users' table in the database.
 *
 * JPA annotations:
 *   @Entity       — marks this class as a JPA-managed entity (maps to a DB table)
 *   @Table        — specifies the exact table name in the database
 *   @Id           — marks the primary key field
 *   @GeneratedValue — auto-increments the ID on each insert
 *   @Column       — customizes column properties (name, uniqueness, nullability)
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class User {

    /**
     * Primary key — auto-generated by the database (IDENTITY strategy).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique login name for the user.
     * - unique = true   → no two users can share the same username
     * - nullable = false → username is required
     * - length = 50     → max 50 characters
     */
    @Column(name = "username", unique = true, nullable = false, length = 50)
    private String username;

    /**
     * Hashed password — NEVER store plain text passwords.
     * Use BCrypt or similar hashing algorithm before saving.
     * - nullable = false → password is required
     */
    @Column(name = "password_hash", nullable = false)
    private String passwordHash;
}
